services:
    _defaults:
        autoconfigure: true

    Ameotoko\IsotopeEvents\Migration\UppercaseLocationCountries:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: contao.migration }

    Ameotoko\IsotopeEvents\EventListener\DatePickerRangeWizard: ~

    Ameotoko\IsotopeEvents\EventListener\ProductLabelCallback:
        arguments:
            - '%kernel.project_dir%'
            - '@contao.image.factory'

    Ameotoko\IsotopeEvents\EventListener\ProductPanelPastFilter:
        arguments:
            - '@request_stack'
